<?php

return [
    [
        'id' => 1,
        'title' => 'Calaborasi E-Commerce',
        'slug' => 'calaborasi-ecommerce',
        'short_desc' => 'Collaborative e-commerce platform with cart, checkout, and payment integration.',
        'full_desc' => 'A full-featured e-commerce platform built collaboratively, featuring product management, shopping cart, checkout flow, and payment gateway integration. Built with modern web technologies to deliver a smooth shopping experience.',
        'features' => [
            'Product catalog with search & filter',
            'Shopping cart & checkout system',
            'Payment gateway integration (Midtrans)',
            'Order management dashboard',
            'Responsive mobile-first design',
        ],
        'tech' => ['Laravel', 'Tailwind', 'Midtrans', 'MySQL'],
        'image' => 'project2.png',
        'screenshots' => [],
        'demo_url' => null,
        'repo_url' => 'https://github.com/Andkhrzald/Calaborasi-Ecommerce',
        'role' => 'Fullstack Developer',
        'timeline' => 'April 2026',
        'collaborators' => ['Rehanfzn'],
    ],
    [
        'id' => 2,
        'title' => 'ELVOAPP V2',
        'slug' => 'elvoapp-v2',
        'short_desc' => 'Task management application built with Laravel and Tailwind CSS.',
        'full_desc' => 'Second version of the ELVOAPP task management system, rebuilt with Laravel for better performance, security, and maintainability. Features real-time task updates, team collaboration, and a clean modern interface.',
        'features' => [
            'Task creation, assignment & tracking',
            'Real-time updates with broadcasting',
            'Team workspace & permissions',
            'Deadline & priority management',
            'Activity log & notifications',
        ],
        'tech' => ['Laravel', 'Tailwind', 'MySQL'],
        'image' => 'DashboardElvo.png',
        'screenshots' => [],
        'demo_url' => null,
        'repo_url' => 'https://github.com/Andkhrzald/ELVOAPP_V2',
        'role' => 'Fullstack Developer',
        'timeline' => 'April 2026',
        'collaborators' => ['Rehanfzn'],
    ],
    [
        'id' => 3,
        'title' => 'Harmoni Nusantara',
        'slug' => 'harmoni-nusantara',
        'short_desc' => 'Cultural platform showcasing Indonesian heritage and arts.',
        'full_desc' => 'A collaborative platform dedicated to preserving and promoting Indonesian cultural heritage. Features interactive galleries, event listings, and educational content about traditional arts, music, and crafts from across the archipelago.',
        'features' => [
            'Cultural heritage articles & galleries',
            'Event calendar & booking system',
            'Artist & artisan profiles',
            'Interactive map of cultural sites',
            'Community forum & discussions',
        ],
        'tech' => ['Laravel', 'Blade', 'Tailwind', 'MySQL'],
        'image' => 'DashboardHarmoni.png',
        'screenshots' => [],
        'demo_url' => null,
        'repo_url' => 'https://github.com/Andkhrzald/harmoni-nusantara',
        'role' => 'Fullstack Developer & Team Lead',
        'timeline' => 'May 2026',
        'collaborators' => ['Rehanfzn', 'FuncSmile', 'NoyanPolicarpus'],
    ],
    [
        'id' => 4,
        'title' => 'ELVOAPP (Flutter)',
        'slug' => 'elvoapp',
        'short_desc' => 'Cross-platform mobile app built with Flutter and Dart.',
        'full_desc' => 'Original ELVOAPP mobile application built with Flutter for cross-platform deployment. Features task management on-the-go with offline support, push notifications, and a clean Material Design interface.',
        'features' => [
            'Cross-platform (Android & iOS)',
            'Offline task management',
            'Push notifications',
            'Cloud sync & backup',
            'Dark mode support',
        ],
        'tech' => ['Flutter', 'Dart', 'API'],
        'image' => 'project3.png',
        'screenshots' => [],
        'demo_url' => null,
        'repo_url' => 'https://github.com/Andkhrzald/ELVOAPP',
        'role' => 'Mobile Developer',
        'timeline' => 'Jan 2026',
        'collaborators' => [],
    ],
];
