<?php

return [
    [
        'id' => 1,
        'title' => 'Calaborasi E-Commerce',
        'slug' => 'calaborasi-ecommerce',
        'short_desc' => 'Collaborative e-commerce platform with cart, checkout, and payment integration.',
        'full_desc' => 'A full-featured e-commerce platform built collaboratively, featuring product management, shopping cart, checkout flow, and payment gateway integration. Built with modern web technologies to deliver a smooth shopping experience.',
        'features' => [
            'Product catalog with search & filter',
            'Shopping cart & checkout system',
            'Payment gateway integration (Midtrans)',
            'Order management dashboard',
            'Responsive mobile-first design',
        ],
        'tech' => ['Laravel', 'Tailwind', 'Midtrans', 'MySQL'],
        'image' => 'project2.png',
        'screenshots' => [],
        'demo_url' => null,
        'repo_url' => 'https://github.com/Andkhrzald/Calaborasi-Ecommerce',
        'role' => 'Fullstack Developer',
        'timeline' => 'April 2026',
        'collaborators' => ['Rehanfzn'],
    ],
    [
        'id' => 2,
        'title' => 'ELVOAPP V2',
        'slug' => 'elvoapp-v2',
        'short_desc' => 'E-Commerce admin dashboard with Laravel and Tailwind CSS.',
        'full_desc' => 'A web-based fashion E-Commerce platform built with Laravel 13, Vite, and TailwindCSS v4. Features integrated inventory management, real-time order tracking, and sales data visualization using ApexCharts. Built collaboratively using Git for team synchronization.',
        'features' => [
            'Auth system with protected Customer & Admin access',
            'Product CRUD, category & review management',
            'Shopping cart, checkout flow & order tracking',
            'Sales data visualization with ApexCharts',
            'Database architecture with Migrations & Seeders',
        ],
        'tech' => ['Laravel', 'Tailwind', 'MySQL', 'ApexCharts'],
        'image' => 'DashboardElvo.png',
        'screenshots' => [],
        'demo_url' => null,
        'repo_url' => 'https://github.com/Andkhrzald/ELVOAPP_V2',
        'role' => 'Fullstack Developer',
        'timeline' => 'April 2026',
        'collaborators' => ['Rehanfzn'],
    ],
    [
        'id' => 3,
        'title' => 'Harmoni Nusantara',
        'slug' => 'harmoni-nusantara',
        'short_desc' => 'Cultural platform showcasing Indonesian heritage and arts.',
        'full_desc' => 'A collaborative platform dedicated to preserving and promoting Indonesian cultural heritage. Features interactive galleries, event listings, and educational content about traditional arts, music, and crafts from across the archipelago.',
        'features' => [
            'Cultural heritage articles & galleries',
            'Event calendar & booking system',
            'Artist & artisan profiles',
            'Interactive map of cultural sites',
            'Community forum & discussions',
        ],
        'tech' => ['Laravel', 'Blade', 'Tailwind', 'MySQL'],
        'image' => 'DashboardHarmoni.png',
        'screenshots' => [],
        'demo_url' => null,
        'repo_url' => 'https://github.com/Andkhrzald/harmoni-nusantara',
        'role' => 'Fullstack Developer & Team Lead',
        'timeline' => 'May 2026',
        'collaborators' => ['Rehanfzn', 'FuncSmile', 'NoyanPolicarpus'],
    ],
    [
        'id' => 4,
        'title' => 'ELVOAPP (Flutter)',
        'slug' => 'elvoapp',
        'short_desc' => 'E-Commerce mobile app built with Flutter and Dart.',
        'full_desc' => 'An E-Commerce mobile application built with Flutter featuring UI/UX design in Figma. Includes customer login system, elegant product dashboard inspired by Zara, Zalora, and Shopee. Built as a university exam project for UI/UX course.',
        'features' => [
            'Customer Login & Register system',
            'Main dashboard with modern product catalog',
            'Responsive and simple navigation',
            'Interactive Figma prototype before coding phase',
            'Cross-platform (Android & iOS)',
        ],
        'tech' => ['Flutter', 'Dart', 'Figma'],
        'image' => 'project3.png',
        'screenshots' => [],
        'demo_url' => null,
        'repo_url' => 'https://github.com/Andkhrzald/ELVOAPP',
        'role' => 'Mobile Developer & UI/UX Designer',
        'timeline' => 'Jan 2026',
        'collaborators' => [],
    ],
];
